### ISSUE TITLE
Confirmation email TODO List

### ISSUE THREAD

**Issue by matiu** [bitpay/wallet#1775]
- [ ] Emails are currently picked by the SPAM filters
- [x] Authorization links do not work
- [x] If the profile is not confirmed, there should be a header in INSIGHT:
  `x-confirmed-profile: false`
- [x]   and the client should show the user a warning message like:

```
   Your email account is not yet confirmed. Please confirm your email account
   to prevent the server to erase you profile.  
   <Click here to resend confirmation email> 
```
