### ISSUE TITLE
Signup UX enhacement TODO List

### ISSUE THREAD

**Issue by matiu** [bitpay/wallet#1776]
- [ ]  When creating a profile, some options should be explained to the user:
  1. Your profile will be created on the Insight server [insight.bitpay.com]. Alternatively, you can:
     1. Choose to store the wallet on your system, and take care of backups by your own.
     2. Run your own Insight server <link>  
  2. The server will have access to your _encrypted_ wallet. Choosing a proper password would prevent the server or any person to access your wallet.
- [ ] After signing up with Insight storage, a message should be shown to the user: 

```
  An email have been sent you xx@yy.com with a confirmation link.  Please confirm
  your email to prevent this profile to get deleted on the server.
```
- [ ] After signing up with  any storage, a message should be shown to the user: 

```
   It is highly recommend that you backup your wallet now before start using it. 
    You should keep the file somewhere safe. The backup will be encrypted with the 
    password you have chosen.
```

Related: Confirmation email enhancements. https://github.com/bitpay/copay/issues/1775
