### ISSUE TITLE
Networking TODO

### ISSUE THREAD

**Issue by matiu** [bitpay/wallet#1892]
- [x] add 'no network' at login 
- [x] test network change
- [x] test network reconnect.
